
title: Kringle KB
name: Greg McMillan
email: gmcmillan100@gm**l.com
description: For technical writers who are building lightweight publishing systems
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

category: [gold, silver, copper]

markdown: kramdown
#theme: jekyll-theme-cayman
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#sass:
#    style: compressed